server:
  port: 9527

#Eureka

spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-zuul #修改eureka 的默认配置
    prefer-ip-address: true
  info:
    app.name:kuang-springcloud
    company.name:blog.kuangstudy.com
