server:
  port: 7001
#Eureka
eureka:
 instance:
   hostname: localhost #Eureka 服务端的实例名称
 client:
    register-with-eureka: false #表示是否向eurake注册中心注册自己
    fetch-registery: false #fasle 表示自己是注册中心
    service-url: #监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

