server:
  port: 80


#开启降级feign.hystrix
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-consumer-dept80 #修改eureka 的默认配置
spring:
  application:
    name: springcloud-consumer-dept-80
feign:
  hystrix:
    enabled: true
